_target_: franka_allegro.deployers.VINNDynamics
data_path: ???

# Directories to change by the user depending on where they saved the data
deployment_dump_dir: ???
tactile_out_dir: /home/aadhithya/Workspace/FrankaAllegro-Policies/franka_allegro/out/2023.12.11/09-16_sponge_picking_tactile
tactile_model_type: byol
image_out_dir: /home/aadhithya/Workspace/FrankaAllegro-Policies/franka_allegro/out/2023.12.10/21-49_sponge_picking
image_model_type: dynamics

nn_buffer_size: 25
nn_k: 25
data_representations: ${data_representations}
representation_types: ['image'] # Observations used in the representations
representation_importance: [1] # We will multiply the distances with these given numbers when using in scaled nearest neighbors
demos_to_use:  [2,4,6,9,10,11,12] # Let's use all LOL
# demos_to_use: [3]

view_num: 0
open_loop: false

dump_deployment_info: false