defaults:
  - deployer: vinn # This fails almost anywhere! 

visualize: false
loop: true
frequency: 4
deployment_dump_dir: dump_multitask_hand_tea_moco_1000_state_dict_data_clean_unprocessed_demo_as_all
demo_to_run: [2]
data_representations: ['image','allegro', 'franka']
data_path: /data/sponge_picking_working/ #/data/infra_test_dataset/R0B1B_test